GENOTYPE_BASE_FILE : "genos01_02_2024/tVulg_thyme2016CoreSampling_maf01_geno005_maf0.1_geno0.05_imiss0.1_r20.1_prunned"
METADATA_FILE : "data/genos01_02_2024/thymus_2016_sample_info_clean233samples.tsv"
