configfile: "workflow/config.yaml"


include: "rules/allele_frequencies.smk"
include: "rules/slim.smk"
include: "rules/misidentified_snps.smk"
include: "rules/quality_control.smk"


rule all:
    input:
        f"results/allele_freqs/{config['GENOTYPE_BASE_FILE']}.csv",
        "steps/misidentified_snps/.done",
